name: day2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.0.0
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - imbalanced-learn=0.12.4
  - lightgbm=4.5.0
  - scipy=1.16.2
  - seaborn=0.13.2
  - statsmodels=0.14.5
  - plotly=6.3.1
  - nbformat=5.10.4
  - ipykernel=6.30.1
  - wfdb=4.3.0
  - matplotlib=3.9.2
  - llvm-openmp        # macOS OpenMP runtime for LightGBM
  - pip
  - pip:
      - miceforest==6.0.5
      - statannotations==0.7.1
